// Created by iWeb 3.0.4 local-build-20131206

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,22),url:'Publications_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Publications_files/stroke_9.png'},{rect:new IWRect(1,-1,286,2),url:'Publications_files/stroke_10.png'},{rect:new IWRect(287,-1,2,2),url:'Publications_files/stroke_11.png'},{rect:new IWRect(287,1,2,22),url:'Publications_files/stroke_12.png'},{rect:new IWRect(287,23,2,2),url:'Publications_files/stroke_13.png'},{rect:new IWRect(1,23,286,2),url:'Publications_files/stroke_14.png'},{rect:new IWRect(-1,23,2,2),url:'Publications_files/stroke_15.png'}],new IWSize(288,24)),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,28),url:'Publications_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Publications_files/stroke_1.png'},{rect:new IWRect(1,-1,651,2),url:'Publications_files/stroke_2.png'},{rect:new IWRect(652,-1,2,2),url:'Publications_files/stroke_3.png'},{rect:new IWRect(652,1,2,28),url:'Publications_files/stroke_4.png'},{rect:new IWRect(652,29,2,2),url:'Publications_files/stroke_5.png'},{rect:new IWRect(1,29,651,2),url:'Publications_files/stroke_6.png'},{rect:new IWRect(-1,29,2,2),url:'Publications_files/stroke_7.png'}],new IWSize(653,30))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Publications_files/PublicationsMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id17');adjustFontSizeIfTooBig('id17');adjustLineHeightIfTooBig('id18');adjustFontSizeIfTooBig('id18');fixupIECSS3Opacity('id2');fixupIECSS3Opacity('id3');fixupIECSS3Opacity('id4');fixupIECSS3Opacity('id5');fixupIECSS3Opacity('id6');fixupIECSS3Opacity('id7');fixupIECSS3Opacity('id8');fixupIECSS3Opacity('id9');fixupIECSS3Opacity('id10');fixupIECSS3Opacity('id11');fixupIECSS3Opacity('id12');fixupIECSS3Opacity('id13');fixupIECSS3Opacity('id14');fixupIECSS3Opacity('id15');applyEffects()}
