// Created by iWeb 3.0.4 local-build-20131203

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({shadow_0:new IWShadow({blurRadius:12,offset:new IWPoint(2.1213,2.1213),color:'#000000',opacity:0.750000}),stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,22),url:'Me_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'Me_files/stroke_17.png'},{rect:new IWRect(1,-1,286,2),url:'Me_files/stroke_18.png'},{rect:new IWRect(287,-1,2,2),url:'Me_files/stroke_19.png'},{rect:new IWRect(287,1,2,22),url:'Me_files/stroke_20.png'},{rect:new IWRect(287,23,2,2),url:'Me_files/stroke_21.png'},{rect:new IWRect(1,23,286,2),url:'Me_files/stroke_22.png'},{rect:new IWRect(-1,23,2,2),url:'Me_files/stroke_23.png'}],new IWSize(288,24)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,28),url:'Me_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Me_files/stroke_9.png'},{rect:new IWRect(1,-1,651,2),url:'Me_files/stroke_10.png'},{rect:new IWRect(652,-1,2,2),url:'Me_files/stroke_11.png'},{rect:new IWRect(652,1,2,28),url:'Me_files/stroke_12.png'},{rect:new IWRect(652,29,2,2),url:'Me_files/stroke_13.png'},{rect:new IWRect(1,29,651,2),url:'Me_files/stroke_14.png'},{rect:new IWRect(-1,29,2,2),url:'Me_files/stroke_15.png'}],new IWSize(653,30)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,136),url:'Me_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'Me_files/stroke_1.png'},{rect:new IWRect(2,-2,130,4),url:'Me_files/stroke_2.png'},{rect:new IWRect(132,-2,4,4),url:'Me_files/stroke_3.png'},{rect:new IWRect(132,2,4,136),url:'Me_files/stroke_4.png'},{rect:new IWRect(132,138,4,4),url:'Me_files/stroke_5.png'},{rect:new IWRect(2,138,130,4),url:'Me_files/stroke_6.png'},{rect:new IWRect(-2,138,4,4),url:'Me_files/stroke_7.png'}],new IWSize(134,140))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Me_files/MeMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');detectBrowser();adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('Media/transparent.gif');IMpreload('Me_files','shapeimage_5','0');applyEffects()}
function onPageUnload()
{Widget.onunload();}
