// Created by iWeb 3.0.4 local-build-20121016

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,22),url:'Other_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Other_files/stroke_9.png'},{rect:new IWRect(1,-1,286,2),url:'Other_files/stroke_10.png'},{rect:new IWRect(287,-1,2,2),url:'Other_files/stroke_11.png'},{rect:new IWRect(287,1,2,22),url:'Other_files/stroke_12.png'},{rect:new IWRect(287,23,2,2),url:'Other_files/stroke_13.png'},{rect:new IWRect(1,23,286,2),url:'Other_files/stroke_14.png'},{rect:new IWRect(-1,23,2,2),url:'Other_files/stroke_15.png'}],new IWSize(288,24)),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,28),url:'Other_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Other_files/stroke_1.png'},{rect:new IWRect(1,-1,651,2),url:'Other_files/stroke_2.png'},{rect:new IWRect(652,-1,2,2),url:'Other_files/stroke_3.png'},{rect:new IWRect(652,1,2,28),url:'Other_files/stroke_4.png'},{rect:new IWRect(652,29,2,2),url:'Other_files/stroke_5.png'},{rect:new IWRect(1,29,651,2),url:'Other_files/stroke_6.png'},{rect:new IWRect(-1,29,2,2),url:'Other_files/stroke_7.png'}],new IWSize(653,30))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Other_files/OtherMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');detectBrowser();adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
